
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'snowflake'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Global configurations
vars:
  # Project-specific variables
  start_date: '2016-01-01'
  end_date: '2020-12-31'
  
# Snapshot configurations
snapshots:
  snowflake:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Seed configurations
seeds:
  snowflake:
    +schema: RAW_DATA
    +quote_columns: false


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# Model configurations for Brazilian E-commerce data pipeline
models:
  snowflake:
    # Staging models: Views in STAGING schema
    staging:
      +materialized: view
      +schema: STAGING
      +docs:
        node_color: "#228B22"  # Green for staging
      +meta:
        layer: "staging"
        
    # Intermediate models: Ephemeral by default (can be overridden in individual files)
    intermediate:
      +schema: STAGING
      +materialized: ephemeral
      +docs:
        node_color: "#FF8C00"  # Orange for intermediate
      +meta:
        layer: "intermediate"
        
    # Mart models: Tables in ANALYTICS schema
    mart:
      +materialized: table
      +schema: ANALYTICS
      +docs:
        node_color: "#4169E1"  # Blue for mart
      +meta:
        layer: "mart"

